#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 suzuki takuma <s23c1076vc@s.chibakoudai.jp>

import sys
ans = 0
for line in sys.stdin:
    try:
        ans += int(lie)
    except:
        ans += float(line)
print(ans)
